use super::{Fixture, inventory};
use axum::{Router, body::Body, extract::Request, response::Response};
use std::{
    fs,
    net::{IpAddr, Ipv4Addr, SocketAddr},
    process::{Child, Command, Stdio},
    sync::{Arc, Mutex},
    time::Duration,
};

struct Process(Child);
impl Drop for Process {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}
struct Server(tokio::task::JoinHandle<()>);
impl Drop for Server {
    fn drop(&mut self) {
        self.0.abort();
    }
}

#[tokio::test]
#[ignore = "requires pinned CADDY_VALIDATOR and loopback TCP; private test CA is trusted only by this process"]
async fn generated_gateway_enforces_auth_methods_and_fixed_read_routes() {
    let binary = std::env::var_os("CADDY_VALIDATOR").expect("verified Caddy binary required");
    for (terrain, players, public_access) in [
        (true, false, false),
        (false, true, false),
        (true, true, false),
        (true, true, true),
    ] {
        let f = Fixture::with_access(terrain, players, public_access);
        let prepared = f.prepare().unwrap();
        let seen = Arc::new(Mutex::new(Vec::new()));
        let seen_request = seen.clone();
        let router = Router::new().fallback(move |request: Request| {
            let seen = seen_request.clone();
            async move {
                seen.lock()
                    .unwrap()
                    .push((request.uri().to_string(), request.headers().clone()));
                Response::builder()
                    .header("content-type", "application/octet-stream")
                    .header("etag", "\"fixture-integrity\"")
                    .header("cache-control", "public, max-age=31536000, immutable")
                    .body(Body::from(vec![0x28, 0xb5, 0x2f, 0xfd, 0x00, 0x80, 0xff]))
                    .unwrap()
            }
        });
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let upstream = listener.local_addr().unwrap();
        let _server = Server(tokio::spawn(async move {
            axum::serve(listener, router).await.unwrap();
        }));
        let port = std::net::TcpListener::bind("127.0.0.1:0")
            .unwrap()
            .local_addr()
            .unwrap()
            .port();
        let gateway = f.root.join("prepared/gateway");
        let storage = f._temp.path().join("caddy-storage");
        let origin = format!("https://map.example.test:{port}");
        // Only test transport/root locations differ. Route/auth directives are
        // generated by the production code; no alternative route fixture.
        let config = fs::read_to_string(gateway.join("Caddyfile")).unwrap()
            .replace("skip_install_trust", &format!("skip_install_trust\n  auto_https disable_redirects\n  storage file_system {{\n    root {}\n  }}", storage.display()))
            .replace("https://map.example.test {", &format!("{origin} {{\n  tls internal\n  bind 127.0.0.1"))
            .replace("/etc/bedrock-map", gateway.to_str().unwrap())
            .replace("/opt/bedrock-map/web", f.resources.web().to_str().unwrap())
            .replace("/srv/map-public", f.root.join("prepared/public").to_str().unwrap())
            .replace("terrain:8111", &upstream.to_string())
            .replace("players:8110", &upstream.to_string());
        let path = f._temp.path().join("Caddyfile-https");
        fs::write(&path, config).unwrap();
        let logfile = f._temp.path().join("gateway.log");
        let log = fs::File::create(&logfile).unwrap();
        let mut process = Process(
            Command::new(&binary)
                .args(["run", "--config"])
                .arg(path)
                .args(["--adapter", "caddyfile"])
                .env("XDG_CONFIG_HOME", f._temp.path().join("xdg-config"))
                .env("XDG_DATA_HOME", f._temp.path().join("xdg-data"))
                .stdout(Stdio::null())
                .stderr(log)
                .spawn()
                .unwrap(),
        );
        let ca = storage.join("pki/authorities/local/root.crt");
        for _ in 0..100 {
            assert!(
                process.0.try_wait().unwrap().is_none(),
                "{}",
                fs::read_to_string(&logfile).unwrap()
            );
            if ca.exists() {
                break;
            }
            tokio::time::sleep(Duration::from_millis(50)).await;
        }
        let client = reqwest::Client::builder()
            .no_proxy()
            .timeout(Duration::from_secs(5))
            .redirect(reqwest::redirect::Policy::none())
            .add_root_certificate(reqwest::Certificate::from_pem(&fs::read(&ca).unwrap()).unwrap())
            .resolve(
                "map.example.test",
                SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), port),
            )
            .build()
            .unwrap();
        for _ in 0..100 {
            if client.get(&origin).send().await.is_ok() {
                break;
            }
            tokio::time::sleep(Duration::from_millis(50)).await;
        }
        let authorize = |request: reqwest::RequestBuilder| {
            request.basic_auth("map", Some("synthetic-only-password"))
        };
        let player_path = format!("/api/v1/worlds/{}/players", prepared.world_id);
        let terrain_path = format!("/api/v1/worlds/{}/terrain/manifest.json", prepared.world_id);
        let public = inventory(&f.root.join("prepared/public"));
        for path in std::iter::once("/".into())
            .chain(public.keys().map(|p| format!("/{p}")))
            .chain([player_path.clone(), terrain_path.clone()])
        {
            let url = format!("{origin}{path}");
            if !public_access {
                assert_eq!(
                    client.get(&url).send().await.unwrap().status(),
                    401,
                    "anonymous {path}"
                );
                assert_eq!(
                    client
                        .get(&url)
                        .basic_auth("map", Some("wrong"))
                        .send()
                        .await
                        .unwrap()
                        .status(),
                    401
                );
            } else {
                assert_eq!(
                    client.get(&url).send().await.unwrap().status(),
                    200,
                    "public {path}"
                );
            }
            let enabled = if path == player_path {
                players
            } else if path == terrain_path {
                terrain
            } else {
                true
            };
            let response = authorize(client.get(&url)).send().await.unwrap();
            assert_eq!(
                response.status(),
                if enabled { 200 } else { 404 },
                "authorized {path}"
            );
            if !public_access {
                assert_eq!(response.headers()["cache-control"], "private, no-store");
            }
            assert_eq!(response.headers()["x-content-type-options"], "nosniff");
        }
        let missing = [
            "/healthz",
            "/config/",
            "/ingest/v1/snapshot",
            "/ingest/v1/terrain",
            "/secrets/players.token",
            "/bds-handoff/config",
            "/preparation.json",
            "/etc/passwd",
            "/index.html/unlisted",
            "/api/v1/worlds/another/players",
            "/%2fetc/passwd",
            "/%252e%252e/deployment.toml",
        ];
        for path in missing {
            let response = authorize(client.get(format!("{origin}{path}")))
                .send()
                .await
                .unwrap();
            assert_eq!(response.status(), 404, "blocked path {path}");
            assert!(response.headers().get("location").is_none());
        }
        // URL clients usually normalize dot segments before sending. curl's
        // raw-path mode verifies refusal of the actual traversal input.
        for path in [
            "/unlisted/../viewer-config.json",
            "/%2e%2e/viewer-config.json",
            "/%2e/viewer-config.json",
            "/maps/../viewer-config.json",
            "//viewer-config.json",
        ] {
            let output = Command::new("curl")
                .args([
                    "--silent",
                    "--show-error",
                    "--noproxy",
                    "*",
                    "--max-time",
                    "5",
                    "--path-as-is",
                    "--cacert",
                ])
                .arg(&ca)
                .args([
                    "--resolve",
                    &format!("map.example.test:{port}:127.0.0.1"),
                    "--user",
                    "map:synthetic-only-password",
                    "--output",
                    "/dev/null",
                    "--write-out",
                    "%{http_code}",
                ])
                .arg(format!("{origin}{path}"))
                .output()
                .unwrap();
            assert!(output.status.success(), "raw-path request failed");
            assert_eq!(
                String::from_utf8(output.stdout).unwrap(),
                "404",
                "raw traversal {path}"
            );
        }
        for method in [
            reqwest::Method::POST,
            reqwest::Method::PUT,
            reqwest::Method::DELETE,
            reqwest::Method::PATCH,
            reqwest::Method::OPTIONS,
        ] {
            let response =
                authorize(client.request(method.clone(), format!("{origin}{player_path}")))
                    .send()
                    .await
                    .unwrap();
            assert_eq!(response.status(), 405, "blocked method {method}");
        }
        let proxy_path = if terrain {
            format!(
                "/api/v1/worlds/{}/terrain/objects/{}.zst",
                prepared.world_id,
                "a".repeat(64)
            )
        } else {
            player_path
        };
        seen.lock().unwrap().clear();
        let response =
            authorize(client.get(format!("{origin}{proxy_path}?upstream=http://evil.invalid")))
                .header("cookie", "viewer-private=canary")
                .header("x-tracker-token", "not-forwarded")
                .header("x-terrain-token", "not-forwarded")
                .header("x-custom-token", "not-forwarded")
                .header("if-none-match", "\"preserved\"")
                .send()
                .await
                .unwrap();
        assert_eq!(response.status(), 200);
        assert_eq!(response.headers()["etag"], "\"fixture-integrity\"");
        assert_eq!(
            response.headers()["content-type"],
            "application/octet-stream"
        );
        assert_eq!(
            response.headers()["cache-control"],
            if public_access {
                "public, max-age=31536000, immutable"
            } else {
                "private, no-store"
            }
        );
        assert!(response.headers().get("content-encoding").is_none());
        assert_eq!(
            response.bytes().await.unwrap().as_ref(),
            &[0x28, 0xb5, 0x2f, 0xfd, 0x00, 0x80, 0xff]
        );
        {
            let seen = seen.lock().unwrap();
            assert_eq!(seen.len(), 1);
            let (_, headers) = &seen[0];
            for name in [
                "authorization",
                "cookie",
                "x-tracker-token",
                "x-terrain-token",
                "x-custom-token",
            ] {
                assert!(
                    !headers.contains_key(name),
                    "sensitive header forwarded: {name}"
                );
            }
            assert_eq!(headers["host"], upstream.to_string());
            assert_eq!(headers["if-none-match"], "\"preserved\"");
        }
        let head = authorize(client.head(format!("{origin}/viewer-config.json")))
            .send()
            .await
            .unwrap();
        assert_eq!(head.status(), 200);
        assert!(head.bytes().await.unwrap().is_empty());
        let binding = authorize(client.get(format!("{origin}/viewer-config.json")))
            .send()
            .await
            .unwrap()
            .text()
            .await
            .unwrap();
        assert!(!binding.contains("packaged-default-only"));
        assert!(binding.contains(&prepared.dataset_id));
        let log = fs::read_to_string(logfile).unwrap();
        assert!(!log.contains("synthetic-only-password") && !log.contains("viewer-private=canary"));
        for service in ["terrain", "players"] {
            let token = f.root.join(format!("secrets/{service}.token"));
            if token.exists() {
                assert!(!log.contains(&fs::read_to_string(token).unwrap()));
            }
        }
    }
}
